SET local check_function_bodies = off;

CREATE TABLE "public"."inventory" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "item"        text                     NOT NULL,
  "amount"      integer,
  "category"    text                     NOT NULL DEFAULT 'other'::text,
  "color"       text,
  "cost"        smallint,
  "url_id"      bigint,
  "author_id"   uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "amount_unit" text                     DEFAULT 'g'::text,
  "cost_unit"   text,
  "color_hex"   text,
  CONSTRAINT "amount_amount_unit_coexist" CHECK ((((amount IS NULL) AND (amount_unit IS NULL)) OR ((amount IS NOT NULL) AND (amount_unit IS NOT NULL)))),
  CONSTRAINT "color_hex_requires_color" CHECK (((color_hex IS NULL) OR (color IS NOT NULL))),
  CONSTRAINT "cost_cost_unit_coexist" CHECK ((((cost IS NULL) AND (cost_unit IS NULL)) OR ((cost IS NOT NULL) AND (cost_unit IS NOT NULL)))),
  CONSTRAINT "inventory_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."inventory"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."materials" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "item"        text                     NOT NULL,
  "amount"      integer                  NOT NULL,
  "category"    text                     NOT NULL DEFAULT '''other''::text'::text,
  "color"       text,
  "cost"        smallint,
  "url_id"      bigint,
  "amount_unit" text                     NOT NULL DEFAULT '''g''::text'::text,
  "pattern_id"  bigint,
  "cost_unit"   text,
  "color_hex"   text,
  CONSTRAINT "amount_amount_unit_coexist" CHECK ((((amount IS NULL) AND (amount_unit IS NULL)) OR ((amount IS NOT NULL) AND (amount_unit IS NOT NULL)))),
  CONSTRAINT "color_hex_requires_color" CHECK (((color_hex IS NULL) OR (color IS NOT NULL))),
  CONSTRAINT "cost_cost_unit_coexist" CHECK ((((cost IS NULL) AND (cost_unit IS NULL)) OR ((cost IS NOT NULL) AND (cost_unit IS NOT NULL)))),
  CONSTRAINT "materials_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."materials"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."owners" (
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "message"    text,
  "pattern_id" bigint                   NOT NULL,
  "user_id"    uuid                     NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT "owners_pkey" PRIMARY KEY (pattern_id, user_id)
);

ALTER TABLE "public"."owners"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."patterns" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "author_id"  uuid                     DEFAULT gen_random_uuid(),
  "url_id"     bigint,
  "rows"       jsonb                    NOT NULL,
  "title"      text                     NOT NULL DEFAULT 'Untitled Pattern'::text,
  "is_editing" boolean                  NOT NULL DEFAULT false,
  CONSTRAINT "patterns_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."patterns"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."stitches" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "shorthand"  text                     NOT NULL DEFAULT ''::text,
  "name"       text                     NOT NULL DEFAULT ''::text,
  "custom"     boolean                  NOT NULL DEFAULT true,
  "origin"     text                     DEFAULT 'US'::text,
  "author_id"  uuid,
  CONSTRAINT "stitches_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."stitches"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."trackers" (
  "id"             uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "current_row"    integer                  NOT NULL DEFAULT 0,
  "current_stitch" text,
  "current_index"  integer                  NOT NULL DEFAULT 0,
  "title"          text                     DEFAULT 'My Tracker'::text,
  "user_id"        uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "pattern_id"     bigint                   NOT NULL,
  "is_finished"    boolean                  NOT NULL DEFAULT false,
  CONSTRAINT "trackers_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."trackers"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."url" (
  "id"      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "url"     text   NOT NULL DEFAULT ''::text,
  "creator" text,
  "brand"   text,
  CONSTRAINT "url_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."url"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_profile" (
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "name"        text,
  "profile_url" text,
  "id"          uuid                     NOT NULL DEFAULT auth.uid(),
  CONSTRAINT "user_profile_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."user_profile"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.insert_owners()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  BEGIN
    INSERT INTO public.owners(pattern_id, user_id)
    VALUES(new.id, new.author_id);
    RETURN new;
  END;
$function$;

CREATE OR REPLACE FUNCTION public.insert_user_profile()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
BEGIN
    INSERT INTO public.user_profile(id, name)
    VALUES(new.id, new.raw_user_meta_data ->> 'username');
    RETURN new;
END;
$function$;

ALTER TABLE "public"."materials"
  ADD CONSTRAINT "materials_pattern_id_fkey" FOREIGN KEY (pattern_id) REFERENCES public.patterns(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."owners"
  ADD CONSTRAINT "owners_pattern_id_fkey" FOREIGN KEY (pattern_id) REFERENCES public.patterns(id) ON DELETE CASCADE;

ALTER TABLE "public"."trackers"
  ADD CONSTRAINT "trackers_user_id_pattern_id_fkey" FOREIGN KEY (user_id, pattern_id) REFERENCES public.owners(user_id, pattern_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."inventory"
  ADD CONSTRAINT "inventory_url_id_fkey" FOREIGN KEY (url_id) REFERENCES public.url(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."materials"
  ADD CONSTRAINT "materials_url_id_fkey" FOREIGN KEY (url_id) REFERENCES public.url(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."patterns"
  ADD CONSTRAINT "patterns_url_id_fkey" FOREIGN KEY (url_id) REFERENCES public.url(id) ON DELETE SET NULL;

CREATE TRIGGER on_user_signup
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.insert_user_profile();

CREATE TRIGGER on_pattern_create
  AFTER INSERT ON public.patterns
  FOR EACH ROW
  EXECUTE FUNCTION public.insert_owners();

CREATE POLICY "Auth users can crud" ON "public"."inventory"
  FOR ALL
  TO "authenticated"
  USING ((auth.uid() = author_id))
  WITH CHECK ((auth.uid() = author_id));

CREATE POLICY "Auth users can read from shared patterns" ON "public"."materials"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.owners
  WHERE ((owners.pattern_id = owners.pattern_id) AND (owners.user_id = auth.uid())))));

CREATE POLICY "Auth users must own pattern for cud" ON "public"."materials"
  FOR ALL
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.patterns
  WHERE ((patterns.id = materials.pattern_id) AND (patterns.author_id = auth.uid())))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.patterns
  WHERE ((patterns.id = materials.pattern_id) AND (patterns.author_id = auth.uid())))));

CREATE POLICY "Auth users can delete" ON "public"."owners"
  FOR DELETE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.patterns
  WHERE ((patterns.id = owners.pattern_id) AND (patterns.author_id = auth.uid())))));

CREATE POLICY "Auth users can share" ON "public"."owners"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.patterns
  WHERE ((patterns.id = owners.pattern_id) AND (patterns.author_id = auth.uid())))));

CREATE POLICY "Auth users can update" ON "public"."owners"
  FOR UPDATE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.patterns
  WHERE ((patterns.id = owners.pattern_id) AND (patterns.author_id = auth.uid())))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.patterns
  WHERE ((patterns.id = owners.pattern_id) AND (patterns.author_id = auth.uid())))));

CREATE POLICY "Select rows with same user_id or is owner of pattern" ON "public"."owners"
  FOR SELECT
  TO "authenticated"
  USING (((auth.uid() = user_id) OR (EXISTS ( SELECT 1
   FROM public.patterns
  WHERE ((patterns.id = owners.pattern_id) AND (patterns.author_id = auth.uid()))))));

CREATE POLICY "Auth users can crud" ON "public"."patterns"
  FOR ALL
  TO "authenticated"
  USING ((auth.uid() = author_id))
  WITH CHECK ((auth.uid() = author_id));

CREATE POLICY "Auth users can edit when < 9 drafts" ON "public"."patterns"
  AS RESTRICTIVE
  FOR UPDATE
  TO "authenticated"
  USING ((author_id = auth.uid()))
  WITH CHECK (((author_id = auth.uid()) AND ((is_editing IS NOT TRUE) OR (( SELECT count(patterns_1.id) AS count
   FROM public.patterns patterns_1
  WHERE ((patterns_1.author_id = auth.uid()) AND (patterns_1.is_editing IS TRUE) AND (patterns_1.id <> patterns.id))) < 9))));

CREATE POLICY "Auth users can only insert when < 9 drafts" ON "public"."patterns"
  AS RESTRICTIVE
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((author_id = auth.uid()) AND ((is_editing IS NOT TRUE) OR (( SELECT count(patterns_1.id) AS count
   FROM public.patterns patterns_1
  WHERE ((patterns_1.author_id = auth.uid()) AND (patterns_1.is_editing IS TRUE))) < 9))));

CREATE POLICY "Auth users can crud" ON "public"."stitches"
  FOR ALL
  TO "authenticated"
  USING ((auth.uid() = author_id))
  WITH CHECK ((auth.uid() = author_id));

CREATE POLICY "Auth users can select predefined" ON "public"."stitches"
  FOR SELECT
  TO "authenticated"
  USING (((auth.uid() = author_id) OR (custom IS FALSE)));

CREATE POLICY "Auth users can crud" ON "public"."trackers"
  FOR ALL
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Auth users can insert if has pattern" ON "public"."trackers"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM public.owners
  WHERE ((owners.user_id = trackers.user_id) AND (owners.pattern_id = trackers.pattern_id))))));

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."patterns";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."stitches";

COMMENT ON TABLE "public"."stitches" IS 'stitch types';

GRANT EXECUTE ON FUNCTION "public"."insert_owners"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."insert_user_profile"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."inventory" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."materials" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."owners" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."patterns" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."stitches" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."trackers" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."url" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_profile" TO "anon", "authenticated", "postgres", "service_role";

ALTER TABLE "public"."user_profile"
  ADD CONSTRAINT "user_profile_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."inventory"
  ADD CONSTRAINT "inventory_author_id_fkey" FOREIGN KEY (author_id) REFERENCES public.user_profile(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."owners"
  ADD CONSTRAINT "owners_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profile(id) ON DELETE CASCADE;

ALTER TABLE "public"."patterns"
  ADD CONSTRAINT "patterns_author_id_fkey" FOREIGN KEY (author_id) REFERENCES public.user_profile(id) ON DELETE SET NULL;

ALTER TABLE "public"."stitches"
  ADD CONSTRAINT "stitches_author_id_fkey" FOREIGN KEY (author_id) REFERENCES public.user_profile(id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE POLICY "Allow auth to select own profile" ON "public"."user_profile"
  FOR SELECT
  TO "authenticated"
  USING ((id = auth.uid()));

